// <auto-generated />
using System;
using Keyless.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Keyless.Infrastructure.Migrations
{
    [DbContext(typeof(KeylessDatabaseContext))]
    partial class KeylessDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Keyless.Domain.Entities.StatisticsGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Accuracy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Consistency")
                        .HasColumnType("numeric");

                    b.Property<int>("CorrectCharacters")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("ExtraCharacters")
                        .HasColumnType("integer");

                    b.Property<int>("IncorrectCharacters")
                        .HasColumnType("integer");

                    b.Property<int>("MissedCharacters")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RawWordsPerMinute")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WordsPerMinute")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CreatedAt", "DurationInSeconds", "UserId");

                    b.ToTable("StatisticsGames");
                });

            modelBuilder.Entity("Keyless.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TestsCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("TestsStarted")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Keyless.Domain.Entities.UserStatsAggregate", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageAccuracy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AverageConsistency")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AverageRawWordsPerMinute")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AverageWordsPerMinute")
                        .HasColumnType("numeric");

                    b.Property<int>("GamesCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("HighestAccuracy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HighestConsistency")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HighestRawWordsPerMinute")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HighestWordsPerMinute")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("UserStatsAggregates");
                });

            modelBuilder.Entity("Keyless.Domain.Entities.StatisticsGame", b =>
                {
                    b.HasOne("Keyless.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Keyless.Domain.Entities.UserStatsAggregate", b =>
                {
                    b.HasOne("Keyless.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
